//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
namespace Base.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CateID { get; set; }
        public string CateName { get; set; }
        public string URL { get; set; }
    }
}
